{{--
    Vue admin pour voir tous les codes de déboursement générés
    À placer dans resources/views/admin/credit-disbursement-codes.blade.php
--}}

<x-layouts.dashboard>
    @php
        $currentLocale = app()->getLocale();
        $t = [
            'title' => [
                'fr' => 'Codes de déboursement',
                'de' => 'Auszahlungscodes',
                'en' => 'Disbursement Codes',
                'es' => 'Códigos de desembolso'
            ],
            'subtitle' => [
                'fr' => 'Liste des codes de déboursement générés par les clients',
                'de' => 'Liste der von Kunden generierten Auszahlungscodes',
                'en' => 'List of disbursement codes generated by clients',
                'es' => 'Lista de códigos de desembolso generados por los clientes'
            ],
            'reference' => [
                'fr' => 'Référence',
                'de' => 'Referenz',
                'en' => 'Reference',
                'es' => 'Referencia'
            ],
            'client' => [
                'fr' => 'Client',
                'de' => 'Kunde',
                'en' => 'Client',
                'es' => 'Cliente'
            ],
            'amount' => [
                'fr' => 'Montant',
                'de' => 'Betrag',
                'en' => 'Amount',
                'es' => 'Monto'
            ],
            'code' => [
                'fr' => 'Code',
                'de' => 'Code',
                'en' => 'Code',
                'es' => 'Código'
            ],
            'generated_at' => [
                'fr' => 'Généré le',
                'de' => 'Generiert am',
                'en' => 'Generated on',
                'es' => 'Generado el'
            ],
            'status' => [
                'fr' => 'Statut',
                'de' => 'Status',
                'en' => 'Status',
                'es' => 'Estado'
            ],
            'actions' => [
                'fr' => 'Actions',
                'de' => 'Aktionen',
                'en' => 'Actions',
                'es' => 'Acciones'
            ],
            'pending_validation' => [
                'fr' => 'En attente de validation',
                'de' => 'Wartet auf Validierung',
                'en' => 'Pending validation',
                'es' => 'Pendiente de validación'
            ],
            'validated' => [
                'fr' => 'Validé',
                'de' => 'Validiert',
                'en' => 'Validated',
                'es' => 'Validado'
            ],
            'expired' => [
                'fr' => 'Expiré',
                'de' => 'Abgelaufen',
                'en' => 'Expired',
                'es' => 'Expirado'
            ],
            'copy_code' => [
                'fr' => 'Copier le code',
                'de' => 'Code kopieren',
                'en' => 'Copy code',
                'es' => 'Copiar código'
            ],
            'view_request' => [
                'fr' => 'Voir la demande',
                'de' => 'Anfrage ansehen',
                'en' => 'View request',
                'es' => 'Ver solicitud'
            ],
            'cancel_code' => [
                'fr' => 'Annuler le code',
                'de' => 'Code stornieren',
                'en' => 'Cancel code',
                'es' => 'Cancelar código'
            ],
        ];
    @endphp

    <!-- Header -->
    <div class="mb-8">
        <h1 class="text-3xl font-bold text-slate-900 mb-2">{{ $t['title'][$currentLocale] }}</h1>
        <p class="text-slate-600">{{ $t['subtitle'][$currentLocale] }}</p>
    </div>

    <!-- Filtres -->
    <div class="mb-6 bg-white rounded-lg border border-slate-200 p-4">
        <div class="flex flex-wrap gap-4">
            <div class="flex items-center space-x-2">
                <span class="text-sm font-medium text-slate-700">Filtre:</span>
                <select id="statusFilter" class="px-3 py-2 border border-slate-300 rounded-lg text-sm">
                    <option value="all">Tous</option>
                    <option value="code_generated">En attente</option>
                    <option value="validated">Validés</option>
                    <option value="expired">Expirés</option>
                </select>
            </div>
        </div>
    </div>

    <!-- Table -->
    <div class="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
        <div class="overflow-x-auto">
            <table class="w-full">
                <thead class="bg-slate-50 border-b border-slate-200">
                    <tr>
                        <th class="px-6 py-4 text-left text-xs font-semibold text-slate-700 uppercase tracking-wider">
                            {{ $t['reference'][$currentLocale] }}
                        </th>
                        <th class="px-6 py-4 text-left text-xs font-semibold text-slate-700 uppercase tracking-wider">
                            {{ $t['client'][$currentLocale] }}
                        </th>
                        <th class="px-6 py-4 text-left text-xs font-semibold text-slate-700 uppercase tracking-wider">
                            {{ $t['amount'][$currentLocale] }}
                        </th>
                        <th class="px-6 py-4 text-left text-xs font-semibold text-slate-700 uppercase tracking-wider">
                            {{ $t['code'][$currentLocale] }}
                        </th>
                        <th class="px-6 py-4 text-left text-xs font-semibold text-slate-700 uppercase tracking-wider">
                            {{ $t['generated_at'][$currentLocale] }}
                        </th>
                        <th class="px-6 py-4 text-left text-xs font-semibold text-slate-700 uppercase tracking-wider">
                            {{ $t['status'][$currentLocale] }}
                        </th>
                        <th class="px-6 py-4 text-left text-xs font-semibold text-slate-700 uppercase tracking-wider">
                            {{ $t['actions'][$currentLocale] }}
                        </th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-slate-200">
                    @forelse($codes as $code)
                        <tr class="hover:bg-slate-50 transition-colors" data-status="{{ $code->disbursement_status }}">
                            <!-- Référence -->
                            <td class="px-6 py-4 whitespace-nowrap">
                                <span class="font-mono text-sm font-semibold text-slate-900">{{ $code->reference_number }}</span>
                            </td>

                            <!-- Client -->
                            <td class="px-6 py-4 whitespace-nowrap">
                                <div>
                                    <p class="font-medium text-slate-900">{{ $code->user->name }}</p>
                                    <p class="text-xs text-slate-500">{{ $code->user->email }}</p>
                                </div>
                            </td>

                            <!-- Montant -->
                            <td class="px-6 py-4 whitespace-nowrap">
                                <span class="font-semibold text-lg text-slate-900">
                                    {{ number_format($code->amount, 2, ',', ' ') }}
                                </span>
                                <span class="text-sm text-slate-600">{{ $code->currency ?? 'CHF' }}</span>
                            </td>

                            <!-- Code -->
                            <td class="px-6 py-4 whitespace-nowrap">
                                @if($code->disbursement_status === 'validated')
                                    <span class="font-mono text-xl font-bold text-slate-400 line-through">{{ chunk_split($code->disbursement_code, 4, ' ') }}</span>
                                @else
                                    <div class="flex items-center space-x-2">
                                        <span class="font-mono text-2xl font-bold text-emerald-600 tracking-wider bg-emerald-50 px-3 py-1 rounded">
                                            {{ chunk_split($code->disbursement_code, 4, ' ') }}
                                        </span>
                                        <button onclick="copyCode('{{ $code->disbursement_code }}')"
                                                class="p-2 text-slate-600 hover:text-emerald-600 hover:bg-emerald-50 rounded transition-colors"
                                                title="{{ $t['copy_code'][$currentLocale] }}">
                                            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"/>
                                            </svg>
                                        </button>
                                    </div>
                                @endif
                            </td>

                            <!-- Date de génération -->
                            <td class="px-6 py-4 whitespace-nowrap text-sm text-slate-600">
                                <div>
                                    <p>{{ $code->disbursement_code_generated_at->format('d/m/Y') }}</p>
                                    <p class="text-xs text-slate-500">{{ $code->disbursement_code_generated_at->format('H:i') }}</p>
                                    <p class="text-xs text-slate-400 mt-1">{{ $code->disbursement_code_generated_at->diffForHumans() }}</p>
                                </div>
                            </td>

                            <!-- Statut -->
                            <td class="px-6 py-4 whitespace-nowrap">
                                @if($code->disbursement_status === 'validated')
                                    <span class="inline-flex items-center px-3 py-1 rounded-full text-xs font-semibold bg-emerald-100 text-emerald-800">
                                        <svg class="w-4 h-4 mr-1" fill="currentColor" viewBox="0 0 20 20">
                                            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"/>
                                        </svg>
                                        {{ $t['validated'][$currentLocale] }}
                                    </span>
                                @elseif($code->disbursement_status === 'expired')
                                    <span class="inline-flex items-center px-3 py-1 rounded-full text-xs font-semibold bg-red-100 text-red-800">
                                        <svg class="w-4 h-4 mr-1" fill="currentColor" viewBox="0 0 20 20">
                                            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd"/>
                                        </svg>
                                        {{ $t['expired'][$currentLocale] }}
                                    </span>
                                @else
                                    <span class="inline-flex items-center px-3 py-1 rounded-full text-xs font-semibold bg-amber-100 text-amber-800 animate-pulse">
                                        <svg class="w-4 h-4 mr-1" fill="currentColor" viewBox="0 0 20 20">
                                            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-12a1 1 0 10-2 0v4a1 1 0 00.293.707l2.828 2.829a1 1 0 101.415-1.415L11 9.586V6z" clip-rule="evenodd"/>
                                        </svg>
                                        {{ $t['pending_validation'][$currentLocale] }}
                                    </span>
                                @endif
                            </td>

                            <!-- Actions -->
                            <td class="px-6 py-4 whitespace-nowrap">
                                <div class="flex items-center space-x-2">
                                    <a href="{{ route('admin.credit-requests.show', ['locale' => $currentLocale, 'id' => $code->id]) }}"
                                       class="text-blue-600 hover:text-blue-800 font-medium text-sm">
                                        {{ $t['view_request'][$currentLocale] }}
                                    </a>

                                    @if($code->disbursement_status !== 'validated')
                                        <form action="{{ route('admin.credit-disbursement.cancel', ['locale' => $currentLocale, 'id' => $code->id]) }}"
                                              method="POST"
                                              onsubmit="return confirm('Voulez-vous vraiment annuler ce code ?')">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit"
                                                    class="text-red-600 hover:text-red-800 font-medium text-sm">
                                                {{ $t['cancel_code'][$currentLocale] }}
                                            </button>
                                        </form>
                                    @endif
                                </div>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="7" class="px-6 py-12 text-center text-slate-500">
                                Aucun code de déboursement généré
                            </td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>

    <!-- Pagination -->
    @if($codes->hasPages())
        <div class="mt-6">
            {{ $codes->links() }}
        </div>
    @endif

    @push('scripts')
    <script>
        // Copier le code dans le presse-papier
        function copyCode(code) {
            navigator.clipboard.writeText(code).then(() => {
                // Afficher une notification
                alert('Code copié: ' + code);
            });
        }

        // Filtrer par statut
        document.getElementById('statusFilter').addEventListener('change', function() {
            const status = this.value;
            const rows = document.querySelectorAll('tbody tr[data-status]');

            rows.forEach(row => {
                if (status === 'all' || row.dataset.status === status) {
                    row.style.display = '';
                } else {
                    row.style.display = 'none';
                }
            });
        });
    </script>
    @endpush
</x-layouts.dashboard>
